# Generated by Django 3.2.9 on 2021-11-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, max_length=2000, upload_to='user_image')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='age')),
            ],
        ),
    ]
