version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: todo-user
      POSTGRES_PASSWORD: 123qweA!
      POSTGRES_DB: todo-db




