# Generated by Django 3.2.9 on 2021-12-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description_project', models.TextField(blank=True, verbose_name='описание')),
                ('link', models.URLField(verbose_name='ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
