# Generated by Django 3.2.9 on 2021-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description_todo', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('link', models.URLField(blank=True, verbose_name='ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_close', models.BooleanField(default=False, verbose_name='is_close')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ManyToManyField(blank=True, to='project.Project')),
            ],
        ),
    ]
