# Generated by Django 3.2.9 on 2021-12-16 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='users',
            field=models.ManyToManyField(db_index=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
