# Generated by Django 3.2.9 on 2021-12-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_link'),
        ('todo', '0002_todo_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
