# Generated by Django 3.2.9 on 2021-12-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_link'),
        ('todo', '0003_alter_todo_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
        migrations.AddField(
            model_name='todo',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='project.Project'),
        ),
    ]
